### ISSUE TITLE
Log directory always empty

### ISSUE THREAD

**Issue by gunnarmorling** [alexcojocaru/elasticsearch-maven-plugin#13] opened 2016-03-03 20:43 UTC
I am not sure whether it's a bug or usage error on my side, but for some reason the log directory is always empty ("elasticsearch-logs"). Is there anything I need to configure to see exception logs there?

I could make it work by adding an slf4j binding as a plug-in dependency and building elasticsearch-maven-plugin from sources, so it contains a log4j.properties file (I'm using log4j); Then I could see at least all exceptions on the Maven console. But clearly that cannot be the right way :)

Any help is highly appreciated!

**Comment by alexcojocaru** [comment] 2016-03-03 21:07
I checked the code in the plugin to set the path.logs directory and it looks good to me.
Setting the logs directory only tells ES to put the log files in there. It doesn't configure any appenders or log levels.

If I read the ES documentation correctly, you can provide your own logging configuration through a file in the config directory (for details see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html#logging). The plugin accepts the configPath property, if you put the logging config file in the config directory which you provide through configPath, it should work.

Let me know if that works for you or not.

**Comment by gunnarmorling** [comment] 2016-03-07 11:27
@alexcojocaru Thanks for your reply, so far I had no luck though :(

Do you maybe have a working example of using the plug-in, configured in a way so actually log output is created in the logs directory? My console hack described above works for now, but it just doesn't feel right ;)

**Comment by alexcojocaru** [comment] 2016-03-09 03:45
I tried a few configuration options, but nothing worked.
The ES documentation on the location of the logging yml file doesn't leave much room for error; and still, nothing I tried generated any log output from ES.

I will look into this when I have more time.

**Comment by alexcojocaru** [comment] 2016-08-07 05:24
Sorry about the delay in replying.

It took me several hours to find out what the root cause of the issue is: I blame it on the ES code, and I implemented a fix in commit https://github.com/alexcojocaru/elasticsearch-maven-plugin/commit/5c2b31f0cc3d7db4fde7043529e5cc16c79f9cc1.
The fix is only in the master branch, I haven't back ported it to the 1.x branch (which has support for ES v1.x).
No release has been built yet, and I have no plans to build one in the foreseeable future - if you still need the fix, let me know and I will build one.

**Comment by alexcojocaru** [comment] 2016-08-16 23:01
I am going to close this issue for the time being; if the logging still doesn't work as expected, it can be re-opened or a new one can be opened.

**Closed by alexcojocaru** 2016-08-16 23:01 UTC

**Comment by gunnarmorling** [comment] 2016-08-17 06:16
Thanks for fixing this! We implemented a workaround on our side for now,
we'll get rid of it once the fix is released. Thanks again.

**Comment by alexcojocaru** [comment] 2016-08-17 16:10
Thanks for getting back to me.
The plugin has just been released; the new version number is 2.2. It will take a few hours before the search index on maven central gets updated.
Let me know if it works as expected.
