### ISSUE TITLE
JUnit integration

### ISSUE THREAD

**Issue by gadieichhorn** [alexcojocaru/elasticsearch-maven-plugin#14] opened 2016-05-15 10:01 UTC
thanks for this plugin!

How do I run integration tests with JUnit against a this test ES instance?

**Comment by gadieichhorn** [comment] 2016-05-15 11:16
managed to find a solution 
using Junit tests annotations I can filter what's running in each phase.

[annotations with JUnit](http://www.rnowak.info/2013/08/integration-tests-with-maven-and-junit.html)

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                    <includes>
                        <include>**/*.class</include>
                    </includes>
                    <excludedGroups>com.test.module.IntegrationTests</excludedGroups>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.19.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <groups>com.test.module.client.IntegrationTests</groups>
                            <includes>
                                <include>**/*.class</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

```

**Comment by alexcojocaru** [comment] 2016-08-02 02:39
Since you found a solution already, I am closing this.

**Closed by alexcojocaru** 2016-08-02 02:39 UTC

**Comment by nitishgoyal13** [comment] 2019-08-07 12:25
I am still not able to run the JUnits using this plugin

Can someone help me figure out how to use this plugin with unit test cases

**Comment by alexcojocaru** [comment] 2019-08-08 05:40
I am not following, Nitish. How are you trying to use this plugin?

**Comment by nitishgoyal13** [comment] 2019-08-08 06:13
Steps : 
1. Start Elasticsearch
2. Run test cases
3. Stop Elasticsearch

But when I use the below config, elasticsearch stops just after starting and it's not up while test cases are running

I want the elasticsearch cluster to be up while executing the test cases and shut it down once the test cases are complete


```<plugin>
				<groupId>com.github.alexcojocaru</groupId>
				<artifactId>elasticsearch-maven-plugin</artifactId>
				<version>6.13</version>
				<configuration>
					<version>6.3.1</version>
					<clusterName>foxtrot</clusterName>
					<transportPort>9300</transportPort>
					<httpPort>9200</httpPort>
				</configuration>
				<executions>
					<execution>
						<id>start-elasticsearch</id>
						<phase>test</phase>
						<goals>
							<goal>runforked</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<executions>
					<execution>
						<id>default-test</id>
						<phase>test</phase>
						<goals>
							<goal>test</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.github.alexcojocaru</groupId>
				<artifactId>elasticsearch-maven-plugin</artifactId>
				<version>6.13</version>
				<configuration>
					<version>6.3.1</version>
					<clusterName>foxtrot</clusterName>
					<transportPort>9300</transportPort>
					<httpPort>9200</httpPort>
				</configuration>
				<executions>
					<execution>
						<id>stop-elasticsearch</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>stop</goal>
						</goals>
					</execution>
				</executions>
			</plugin>```

**Comment by alexcojocaru** [comment] 2019-08-08 18:02
The problem is you're starting and stopping ES in the same maven phase as your unit tests. What maven is going to do is to start ES and then stop ES before or after running your unit tests.
My recommendation is to use ES for integration tests, not for unit tests; that's why the examples in the README bind the start to the *pre-integration-test* and the stop to the *post-integration-test*; the failsafe plugin will execute the integration tests in the *integration-test* phase, during which ES is running.
If you insist on using ES for unit testing, I suggest starting it in a phase prior to *test* and stopping it in a phase after *test*. Have a look at the default lifecycle phases (https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) , more specifically which phases come before *test* and which come after. You'd want to bind the start the a phase before *test* and stop to a phase after *test*.
