### ISSUE TITLE
elasticsearch-maven-plugin:6.12:runforked (start-elasticsearch) hangs forever

### ISSUE THREAD

**Issue by SimoneCafiero** [alexcojocaru/elasticsearch-maven-plugin#90] opened 2019-05-15 10:22 UTC
Hi,
sometimes I experience that the **mvn verify** execution blocks at the following message:

_elasticsearch-maven-plugin:6.13:runforked (start-elasticsearch)_

If I kill the process and restart it, it happens again... Till now, just a reboot fixes it. Variation of <timeout> did not fix it (actually it looks to be ignored).

ES 7.0.1. Maybe connected to some resource being created and not destroyed during previous execution that locks the correct execution? Or maybe connected to memory given to ES? Running -X doesn't show meaningful info.

**Comment by SimoneCafiero** [comment] 2019-05-15 10:37
So I went through the two possibilities:

- memory did not change the issue, as I was already giving it 2GB
- it looks like **elasticsearch.keystore.tmp** was the problem, being created from previous execution and that locked current/next ones.

Hope that helps somebody facing the exact same issue.

**Comment by alexcojocaru** [comment] 2019-05-16 05:31
Could you provide more details on the root cause and how you fixed it? I cannot reproduce the issue on Macos; when ES starts up (by the plugin, during the _integration-test_ phase), it creates an _elasticsearch.keystore_ file in target/elasticsearch0/config which is owned by the current user. A subsequent `mvn verify` or `mvn clean verify` would start ES just fine.

**Comment by alexcojocaru** [comment] 2019-06-30 20:59
Still cannot reproduce the issue with the same plugin and ES versions as  yours. I am closing this issue due to lack of details.

**Closed by alexcojocaru** 2019-06-30 20:59 UTC
