### ISSUE TITLE
Failed to obtain node locks when running in TravisCI

### ISSUE THREAD

**Issue by hakdogan** [alexcojocaru/elasticsearch-maven-plugin#53] opened 2017-12-04 13:44 UTC
Hi.

The build process is working without any problems in my locally but fails in TravisCI.

[The Build](https://travis-ci.org/hakdogan/ElasticSearch/builds/311302318)
```
[2017-12-04T13:24:40,213][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/home/travis/build/hakdogan/ElasticSearch/target/elasticsearch0/data/test]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.4.jar:5.6.4]
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/home/travis/build/hakdogan/ElasticSearch/target/elasticsearch0/data/test]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:261) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.4.jar:5.6.4]
	... 6 more
```

``travis.yml``
```
language: java
jdk:
- oraclejdk8
sudo: true
script: mvn clean install

before_script:
  - sudo sysctl -w vm.max_map_count=262144

after_success:
- mvn clean cobertura:cobertura coveralls:report

deploy:
  provider: releases
  skip_cleanup: true

  on:
    tags: true
    all_branches: true
    repo: hakdogan/ElasticSearch
```
``pom.xml``
```
<plugin>
                <groupId>com.github.alexcojocaru</groupId>
                <artifactId>elasticsearch-maven-plugin</artifactId>
                <version>6.0</version>
                <configuration>
                    <version>5.6.4</version>
                    <clusterName>test</clusterName>
                    <transportPort>9300</transportPort>
                    <httpPort>9200</httpPort>
                    <timeout>120</timeout>
                </configuration>
                <executions>
                    <execution>
                        <id>run</id>
                        <phase>process-test-resources</phase>
                        <goals>
                            <goal>runforked</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>start-elasticsearch</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>runforked</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>stop-elasticsearch</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
I haven't found anything like this between the issues. The problem seems to be write permission, any idea?

**Comment by dadoonet** [comment] 2017-12-04 15:41
The problem IMO is that there is already a node running in this dir.
Do you run multiple builds in parallel?

**Comment by hakdogan** [comment] 2017-12-04 17:14
Hi David,

> Do you run multiple builds in parallel?

No. The build process was triggered by GitHub and it should be single.

**Comment by hakdogan** [comment] 2017-12-04 17:45
> So may be one of the previous run did not stopped correctly?
In that case a mvn clean install should do the trick as it will cleanup the target/elasticsearch0/data dir.

You're right.

But the target directory is not sent by push.

[.gitignore](https://github.com/hakdogan/ElasticSearch/blob/master/.gitignore) file of the repository.

**Comment by dadoonet** [comment] 2017-12-04 17:47
Yeah but you said you run that in Jenkins, right?
I believe that your Jenkins work folder is not cleaned between runs.

So you still have may be something there which is coming from a previous run of the job.

**Comment by hakdogan** [comment] 2017-12-04 17:51
> Yeah but you said you run that in Jenkins, right?

No, I did not say that.

I'm using maven for this project.

**Comment by dadoonet** [comment] 2017-12-04 17:53
Oh sorry. I meant `TravisCI`. You are running that on TravisCI, right?

**Comment by hakdogan** [comment] 2017-12-04 17:55
> Oh sorry. I meant TravisCI. You are running that on TravisCI, right?

Yes.

What are you suggesting?

**Comment by dadoonet** [comment] 2017-12-04 18:12
Hmmm. So I looked at the [full logs](https://travis-ci.org/hakdogan/ElasticSearch/builds/311302318).

There is first this:

```
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
```

And then:

```
mvn clean install
```

With a first run of the maven plugin:

```
[2017-12-04T13:24:09,099][INFO ][o.e.n.Node               ] [] initializing ...
```



And then another one but the previous one is not stopped:

```
[2017-12-04T13:24:40,147][INFO ][o.e.n.Node               ] [] initializing ...
```

That explains why you are getting this error.

I believe this is caused by:

https://github.com/hakdogan/ElasticSearch/blob/master/pom.xml#L162-L168

Where it's is executed all the time but never stopped?

**Comment by hakdogan** [comment] 2017-12-04 18:36
Hi David,

First, thank you so much.

I have added the process-test-resources phase for tests because the tests need an ElasticSearch instance. The build will fail without the phase but I have tried it to see the situation.

And it was not a surprise, it failed :((

I guess I should try a different solution for unit tests.

**Comment by dadoonet** [comment] 2017-12-04 18:39
Unit tests should never rely on an external service IMO.

**Comment by hakdogan** [comment] 2017-12-04 18:47
> Unit tests should never rely on an external service IMO.

Yep.

But we can think of the instance as internal service provides by this plugin.

Am I wrong?

**Comment by dadoonet** [comment] 2017-12-04 18:55
So it's not unit tests but integration tests IMO.

**Comment by alexcojocaru** [comment] 2017-12-13 06:24
I agree with @dadoonet on this one: unit tests should not use external services; instead, they should mock all their dependencies.

If I read your plugin config correctly, the plugin is ran twice (once in the `process-test-resources` phase, then again in the `pre-integration-test` phase). The second run should fail.
If you really want to go this route and use a real ES instance for unit testing, make sure you stop it after that phase and before running it again. Even so, it is possible that the 2nd run will fail, for I have never tested this scenario: run-forked, stop, run-forked.

I am going to close this issue unless you have other reasons for keeping it open.

**Comment by hakdogan** [comment] 2017-12-13 08:44
Hi @alexcojocaru 

It can be closed because of that I haven't other reasons.

Thank you both.

**Closed** 2017-12-15 06:45 UTC
