### ISSUE TITLE
 Failed to execute goal com.github.alexcojocaru:elasticsearch-maven-plugin:6.13:runforked (start-elasticsearch) on project website: This Elasticsearch process destroyer does not support this operation

### ISSUE THREAD

**Issue by lekeDevOps** [alexcojocaru/elasticsearch-maven-plugin#111] opened 2020-06-11 11:22 UTC
Why do we get this? @alexcojocaru?

**Comment by alexcojocaru** [comment] 2020-06-12 03:37
I don't know why you are getting this but, with some help from you, we could try getting to the bottom of it, solve your issue and potentially fixing a bug in the plugin.
I need to know more about your setup. Which OS do you use? Is it a containerized build? Is it happening consistently? Can you provide a pom.xml to reproduce the error? Where in the execution flow is the exception thrown? Try setting the `logLevel` property on the plugin to `DEBUG`, that would make the plugin more verbose and provide more details - and send me those logs (if there is any sensitive info in them, make sure to clear it).

**Comment by alexcojocaru** [comment] 2020-06-18 03:49
It appears you are not interested in following up on this.
Since the info you provided is not sufficient to investigate the issue, I am closing it.

**Closed by alexcojocaru** 2020-06-18 03:49 UTC
